services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        ports:
            - '5432:5432'
        command: postgres -c 'max_connections=1000'
        environment:
            - POSTGRES_USER=db-lens
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=postgres
            - PGPORT=5432
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 5s
        volumes:
            - ./db/init.postgre.sql:/docker-entrypoint-initdb.d/init.sql
