name: Pull Request
on:
    pull_request:

permissions:
    contents: write
    packages: write

jobs:
    test-unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Run tests
              shell: bash
              run: npm test

    test-extension:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              shell: bash
              run: npm install
            - name: Run tests
              shell: bash
              run: xvfb-run -a npm run test:vscode

    test-webview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              working-directory: webview-ui
              shell: bash
              run: npm install
            - name: Run tests
              working-directory: webview-ui
              shell: bash
              run: npm test

    test-e2e:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install code dependencies
              shell: bash
              run: npm install
            - name: Install e2e tests dependencies
              working-directory: e2e
              shell: bash
              run: npm install
            - name: Start services
              working-directory: e2e
              shell: bash
              run: npm run test:prepare
            - name: Run tests
              working-directory: e2e
              shell: bash
              run: npm test
            - name: Stop services
              if: always()
              working-directory: e2e
              shell: bash
              run: npm run test:stop
